apiVersion: v1
kind: Pod
metadata:
  name: bigdata2-primary
  labels:
    app: bigdata2-primary
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
  restartPolicy: Always
  containers:
  - name: bigdata2-primary
    image: diegofpsouza/bigdata2:0.0.1
    imagePullPolicy: Always
    env:
      - name: MODE
        value: primary
    ports:
      - containerPort: 8080
      - containerPort: 7077
      - containerPort: 9000
      - containerPort: 8032
      - containerPort: 8088
      - containerPort: 9864
      - containerPort: 9870
      - containerPort: 19888
      - containerPort: 8042
      - containerPort: 9046

