kind: Service
apiVersion: v1
metadata:
  name: spark-primary
spec:
  ports:
    - name: p1
      port: 4040
      targetPort: 4040
    - name: p2
      port: 7077
      targetPort: 7077
    - name: p3
      port: 8080
      targetPort: 8080
    - name: p4
      port: 18080
      targetPort: 18080
  selector:
    app: spark-primary
  type: LoadBalancer
