apiVersion: v1
kind: Service
metadata:
  name: monitor1-frontend-svc
  namespace: default
spec:
  selector:
    app: monitor1-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  clusterIP: None
  type: ClusterIP