apiVersion: v1
kind: Service
metadata:
  name: monitor1-mongo-svc
spec:
  selector:
    app: monitor1-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None
  type: ClusterIP