apiVersion: v1
kind: Service
metadata:
  name: monitor1-nginx-svc
  namespace: default
spec:
  selector:
    app: monitor1-nginx
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer