apiVersion: v1
kind: Service
metadata:
  name: monitor1-rabbit-svc
spec:
  selector:
    app: monitor1-rabbit
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
  clusterIP: None
  type: ClusterIP