apiVersion: v1
kind: Service
metadata:
  name: monitor1-backend-svc
  namespace: default
spec:
  selector:
    app: monitor1-backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  clusterIP: None
  type: ClusterIP