# Default values for openalpr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  source: diegofpsouza
  name: demo_ws_openalpr
  tag: 0.0.1
  csd_pods: 56
  host_pods: 64
  port: 4568

loadbalancer:
  source: diegofpsouza
  name: loadbalancer
  tag: 0.0.1
  pods: 1
  apiserver: https://10.1.1.1:6443
  strategy: ADAPTIVE_WEIGHT
  port: 4570
  apiserver-keys: ~/.ngd/keys/

