{{- $fullname := include "openalpr.fullname" . -}}
{{- $lbname := printf "%s-loadbalancer" $fullname -}}
{{- $labelname := printf "%s-%s" $fullname .Values.app.name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $lbname }}
  labels:
    app: {{ $lbname }}
spec:
  replicas: {{ .Values.loadbalancer.pods }}
  selector:
    matchLabels:
      app: {{ $lbname }}
  template:
    metadata:
      labels:
        app: {{ $lbname }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - perl
                - host.local
      containers:
      - name: {{ $lbname }}
        image: {{ .Values.loadbalancer.source }}/{{ .Values.loadbalancer.name }}:{{ .Values.loadbalancer.tag }}
        imagePullPolicy: Always
        env:
        - name: APP_NAME
          value: {{ $labelname | quote }}
        - name: SSH_USER
          value: "ngd"
        - name: NUM_THREADS
          value: "16"
        - name: REFRESH_SECONDS
          value: "5"
        - name: API_SERVER
          value: {{ .Values.loadbalancer.apiserver | quote }}
        - name: SELF_SERVER
          value: "http://localhost:4570"
        - name: STRATEGY
          value: {{ .Values.loadbalancer.strategy | quote }}
        - name: MIN_CPU_FOR_WEIGHT
          value: "0.9"
        - name: MOVING_AVERAGE_LEN
          value: "1"
        - name: ON_BUSY
          value: "1"
        - name: TIME_TO_WEIGHT
          value: "time_to_weight_3"
        ports:
        - containerPort: {{ .Values.loadbalancer.port }}
