{{- $appname := include "openalpr.fullname" . -}}
{{- $svcname := printf "svc-%s" $appname -}}
{{- $lbname := printf "%s-loadbalancer" $appname -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $svcname }}
spec:
  selector:
    app: {{ $lbname }}
  ports:
    - protocol: TCP
      port: {{ .Values.loadbalancer.port }}
      targetPort: {{ .Values.loadbalancer.port }}
  type: LoadBalancer
