{{- $cron := include "cron" . -}}
{{- $mongoSvc := include "mongoSvc" . -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $cron }}
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                      - node4
                      - node4.local
          restartPolicy: OnFailure
          containers:
          - name: {{ $cron }}
            image: diegofpsouza/monitor1-cron:0.0.1
            volumeMounts:
            - name: storage-cron
              mountPath: /target_cron
            env:
              - name: TARGET
                value: /target_cron
              - name: MONGOSERVER
                value: {{ $mongoSvc }}
              - name: MONGOUSER
                value: {{ .Values.mongo.user }}
              - name: MONGOPASS
                value: {{ .Values.mongo.pass }}
              - name: MONGOPORT
                value: {{ .Values.mongo.port | quote }}
              - name: BUFFERSIZE
                value: {{ .Values.cron.buffersize | quote }}
          volumes:
          - name: storage-cron
            hostPath:
              path: {{ .Values.cron.hosttarget }}
