{{- $monitor := include "monitor" . -}}
{{- $mongoSvc := include "mongoSvc" . -}}
{{- $rabbitSvc := include "rabbitSvc" . -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $monitor }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ $monitor }}
spec:
  selector:
    matchLabels:
      name: {{ $monitor }}
  template:
    metadata:
      labels:
        name: {{ $monitor }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - arm64
      terminationGracePeriodSeconds: 5
      containers:
      - name: {{ $monitor }}
        image: diegofpsouza/monitor1-monitor:0.0.1
        imagePullPolicy: Always
        volumeMounts:
        - name: storage
          mountPath: /target
        env:
          - name: HOSTHOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: HOSTTARGET
            value: {{ .Values.monitor.hosttarget }}
          - name: TARGET
            value: /target
          - name: MONGOSERVER
            value: {{ $mongoSvc }}
          - name: MONGOUSER
            value: {{ .Values.mongo.user }}
          - name: MONGOPASS
            value: {{ .Values.mongo.pass }}
          - name: MONGOPORT
            value: {{ .Values.mongo.port | quote }}
          - name: RABBITMQSERVER
            value: {{ $rabbitSvc }}
      volumes:
      - name: storage
        hostPath:
          path: {{ .Values.monitor.hosttarget }}
