{{- $backend := include "backend" . -}}
{{- $mongoSvc := include "mongoSvc" . -}}
{{- $rabbitSvc := include "rabbitSvc" . -}}
apiVersion: v1
kind: Pod
metadata:
  name: {{ $backend }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ $backend }}
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - node2
              - node2.local
  restartPolicy: Always
  terminationGracePeriodSeconds: 5
  containers:
  - name: {{ $backend }}
    image: diegofpsouza/monitor1-backend:0.0.1
    imagePullPolicy: Always
    ports:
      - name: web
        containerPort: 8081
        protocol: TCP
    env:
      - name: FLASK_ENV
        value: production
      - name: RABBITMQSERVER
        value: {{ $rabbitSvc }}
      - name: MONGOSERVER
        value: {{ $mongoSvc }}
      - name: MONGOUSER
        value: {{ .Values.mongo.user }}
      - name: MONGOPASS
        value: {{ .Values.mongo.pass }}
      - name: MONGOPORT
        value: {{ .Values.mongo.port | quote }}
