{{- $rabbit := include "rabbit" . -}}
apiVersion: v1
kind: Pod
metadata:
  name: {{ $rabbit }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ $rabbit }}
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - perl
            - host.local
  restartPolicy: Always
  containers:
  - name: {{ $rabbit }}
    image: rabbitmq:3
    ports:
      - name: web
        containerPort: 5672
        protocol: TCP
