{{- $mongo := include "mongo" . -}}
apiVersion: v1
kind: Pod
metadata:
  name: {{ $mongo }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ $mongo }}
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - perl
            - host.local
  restartPolicy: Always
  containers:
  - name: {{ $mongo }}
    image: mongo:latest
    ports:
      - name: web
        containerPort: {{ .Values.mongo.port }}
        protocol: TCP
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: {{ .Values.mongo.user }}
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: {{ .Values.mongo.pass }}

