{{- $frontend := include "frontend" . -}}
apiVersion: v1
kind: Pod
metadata:
  name: {{ $frontend }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ $frontend }}
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - node3
              - node3.local
  restartPolicy: Always
  containers:
  - name: {{ $frontend }}
    image: diegofpsouza/monitor1-frontend:0.0.1
    imagePullPolicy: Always
    ports:
      - name: web
        containerPort: 8080
        protocol: TCP