{{- $backend := include "backend" . -}}
{{- $backendSvcName := include "backendSvcName" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $backendSvcName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ $backend }}
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  clusterIP: None
  type: ClusterIP