{{- $frontend := include "frontend" . -}}
{{- $frontendSvcName := include "frontendSvcName" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $frontendSvcName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ $frontend }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  clusterIP: None
  type: ClusterIP