{{- $mongo := include "mongo" . -}}
{{- $mongoSvcName := include "mongoSvcName" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $mongoSvcName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ $mongo }}
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None
  type: ClusterIP