{{- $nginx := include "nginx" . -}}
{{- $nginxSvcName := include "nginxSvcName" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $nginxSvcName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ $nginx }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  type: LoadBalancer