{{- $loadbalancer := include "loadbalancer" . -}}
{{- $app := include "app" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $loadbalancer }}
  labels:
    app: {{ $loadbalancer }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $loadbalancer }}
  template:
    metadata:
      labels:
        app: {{ $loadbalancer }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - name: {{ $loadbalancer }}
        image: {{ .Values.loadbalancer.image }}
        imagePullPolicy: Always
        volumeMounts:
        - name: keys
          mountPath: /keys
        env:
        - name: APP_NAME
          value: {{ $app }}
        - name: REFRESH_SECONDS
          value: "5"
        - name: API_SERVER
          value: {{ .Values.loadbalancer.apiserver | quote }}
        - name: SELF_SERVER
          value: "http://localhost:4570"
        - name: STRATEGY
          value: {{ .Values.loadbalancer.strategy | quote }}
        - name: MIN_CPU_FOR_WEIGHT
          value: "0.9"
        - name: MOVING_AVERAGE_LEN
          value: "1"
        - name: ON_BUSY
          value: "1"
        - name: TIME_TO_WEIGHT
          value: "time_to_weight_3"
        ports:
        - containerPort: 4570
      volumes:
      - name: keys
        hostPath:
          path: {{ .Values.loadbalancer.apiserverkeys -}}
