{{- $loadbalancerSvc := include "loadbalancerSvc" . -}}
{{- $loadbalancer := include "loadbalancer" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $loadbalancerSvc }}
spec:
  selector:
    app: {{ $loadbalancer }}
  ports:
    - protocol: TCP
      port: {{ .Values.loadbalancer.port }}
      targetPort: 4570
  type: LoadBalancer
