apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hadoop-worker
  labels:
    app: hadoop-worker
spec:
  selector:
    matchLabels:
      name: hadoop-worker
  template:
    metadata:
      labels:
        name: hadoop-worker
    spec:
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - arm64
      containers:
        - name: hadoop-worker
          image: diegofpsouza/bigdata_hadoop:0.0.1
          imagePullPolicy: Always
          env:
            - name: HADOOP_MODE
              value: data
          ports:
            - containerPort: 9864
