apiVersion: v1
kind: Pod
metadata:
  name: hadoop-master
  labels:
    app: hadoop-master
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
  restartPolicy: Always
  containers:
  - name: hadoop-master
    image: diegofpsouza/bigdata_hadoop:0.0.1
    imagePullPolicy: Always
    env:
      - name: HADOOP_MODE
        value: master
    ports:
      - containerPort: 9000
      - containerPort: 8032
      - containerPort: 8088
      - containerPort: 9864
      - containerPort: 9870
      - containerPort: 19888
      - containerPort: 8042
      - containerPort: 9046

