apiVersion: v1
kind: Pod
metadata:
  name: spark-master
  labels:
    app: spark-master
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
  restartPolicy: Always
  containers:
  - name: spark-master
    image: diegofpsouza/bigdata_spark:0.0.1
    imagePullPolicy: Always
    env:
      - name: SPARK_MODE
        value: master
    ports:
      - containerPort: 8080
      - containerPort: 7077

